# Generated by Django 5.0.6 on 2024-06-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='battery_current',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='battery_power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='last_data_transfer_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='last_pass_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='outside_humidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='outside_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='signal_strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='solar_current',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='solar_power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='solar_voltage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='controller',
            name='imai',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='record',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='record',
            name='voltage',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='record',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
